export class EmployeeRec {
 
    constructor(
        public EmployeeID?: number,
        public EmployeeNumber?: string,
        public Title?: string,
        public JMB?: string,
        public FirstName?: string,
        public MiddleName?: string,
        public LastName?: string,    
        public BrSocOsig?: string,
        public Opc_Stanovanja?: string,
        public Djeca?: number,
        public RadnoMjesto?: number,
        public PostalCode?: string,
        public DepartmentID?: number,    
        public OfficeLocation?: string,
        public Dat_Rodjenja?: string,
        public Dat_Zaposl?: string,
        public Dat_Odlaska?: string,
        public Aktivan?: boolean,
        public Razlog_Odlaska?: string,    
        public DepartmentUP?: number,
        public Pol?: string,
        public ImeRoditelja?: string,
        public Broj_LK?: string,
        public Mjesto_LK?: string,
        public Opcina_LK?: string,    
        public Drzavljanstvo?: string,
        public Narod?: string,
        public BracnoStanje?: string,
        public emp_hm_telephone?: string,
        public emp_hm_mobile?: string,
        public emp_oth_email?: string,   
        public emp_work_extphone?: string,
        public emp_work_telephone?: string,
        public emp_work_mobile?: string,   
        public emp_work_email?: string,
        public emp_work_default_email?: number,
        public emp_username?: string,
        public work_station?: number,
        public emp_email_exclude?: string                                                                     
        ) {}
}